from numpy import einsum
from numpy.typing import NDArray
from chem.hf.ghf_data import GHF_Data
from chem.ccsd.ghf_ccsd import GHF_CCSD_Data


def get_cc_j_doubles_doubles(
    ghf_data: GHF_Data,
    ghf_ccsd_data: GHF_CCSD_Data,
) -> NDArray:
    """ tensor_subscripts: ('a', 'b', 'j', 'i', 'c', 'd', 'l', 'k') """
    f = ghf_data.f
    g = ghf_data.g
    kd =  ghf_data.identity_singles
    v = ghf_data.v
    o = ghf_data.o
    t1 = ghf_ccsd_data.t1
    t2 = ghf_ccsd_data.t2
    
    contracted_intermediate = -1.00 * einsum('ac,bd,ik,lj->abjicdlk', kd[v, v], kd[v, v], kd[o, o], f[o, o], optimize=['einsum_path', (0, 1, 2, 3)])
    cc_j_doubles_doubles =  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,jk,li->abjicdlk', kd[v, v], kd[v, v], kd[o, o], f[o, o], optimize=['einsum_path', (0, 1, 2, 3)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('bd,ik,jl,ac->abjicdlk', kd[v, v], kd[o, o], kd[o, o], f[v, v], optimize=['einsum_path', (0, 1, 2, 3)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abijdclk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,ik,jl,bc->abjicdlk', kd[v, v], kd[o, o], kd[o, o], f[v, v], optimize=['einsum_path', (0, 1, 2, 3)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abijdclk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,ik,jl,mc,bm->abjicdlk', kd[v, v], kd[o, o], kd[o, o], f[o, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,ik,jl,md,bm->abjicdlk', kd[v, v], kd[o, o], kd[o, o], f[o, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,jk,le,ei->abjicdlk', kd[v, v], kd[v, v], kd[o, o], f[o, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bd,jl,ke,ei->abjicdlk', kd[v, v], kd[v, v], kd[o, o], f[o, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,klij->abjicdlk', kd[v, v], kd[v, v], g[o, o, o, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('bd,ik,lacj->abjicdlk', kd[v, v], kd[o, o], g[o, v, v, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abjidckl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('bd,jk,laci->abjicdlk', kd[v, v], kd[o, o], g[o, v, v, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abjidckl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,ik,lbcj->abjicdlk', kd[v, v], kd[o, o], g[o, v, v, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abjidckl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,lbci->abjicdlk', kd[v, v], kd[o, o], g[o, v, v, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abjidckl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ik,jl,abcd->abjicdlk', kd[o, o], kd[o, o], g[v, v, v, v], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,ik,mlcj,bm->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,ik,mldj,bm->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,klej,ei->abjicdlk', kd[v, v], kd[v, v], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bd,ik,mlej,em->abjicdlk', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,mlci,bm->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,jk,mldi,bm->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,jk,mlei,em->abjicdlk', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ik,jl,macd,bm->abjicdlk', kd[o, o], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('bd,jk,lace,ei->abjicdlk', kd[v, v], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abijdclk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('bd,jl,kace,ei->abjicdlk', kd[v, v], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abijdclk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('bd,ik,jl,mace,em->abjicdlk', kd[v, v], kd[o, o], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abijdclk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,lbce,ei->abjicdlk', kd[v, v], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abijdclk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,jl,kbce,ei->abjicdlk', kd[v, v], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abijdclk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,ik,jl,mbce,em->abjicdlk', kd[v, v], kd[o, o], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->abjidclk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->abijdclk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('jk,mlcd,abim->abjicdlk', kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (1, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('jl,mkcd,abim->abjicdlk', kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (1, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('ik,jl,nmcd,abnm->abjicdlk', kd[o, o], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,klce,ebij->abjicdlk', kd[v, v], g[o, o, v, v], t2, optimize=['einsum_path', (1, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,mlce,ebim->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,jl,mkce,ebim->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('ad,ik,jl,nmce,ebnm->abjicdlk', kd[v, v], kd[o, o], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,klde,ebij->abjicdlk', kd[v, v], g[o, o, v, v], t2, optimize=['einsum_path', (1, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,jk,mlde,ebim->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,jl,mkde,ebim->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('ac,ik,jl,nmde,ebnm->abjicdlk', kd[v, v], kd[o, o], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('ac,bd,klef,efij->abjicdlk', kd[v, v], kd[v, v], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('ac,bd,jk,mlef,efim->abjicdlk', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('ac,bd,jl,mkef,efim->abjicdlk', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ik,jl,nmcd,am,bn->abjicdlk', kd[o, o], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,mlce,bm,ei->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,jl,mkce,bm,ei->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,ik,jl,nmce,bn,em->abjicdlk', kd[v, v], kd[o, o], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (1, 3), (1, 3), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,jk,mlde,bm,ei->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,jl,mkde,bm,ei->abjicdlk', kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,ik,jl,nmde,bn,em->abjicdlk', kd[v, v], kd[o, o], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (1, 3), (1, 3), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bd,klef,ej,fi->abjicdlk', kd[v, v], kd[v, v], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,jk,mlef,em,fi->abjicdlk', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (1, 2), (1, 3), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bd,jl,mkef,em,fi->abjicdlk', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (1, 2), (1, 3), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abjicdlk->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abjicdlk->bajicdlk', contracted_intermediate)  +  1.00000 * einsum('abjicdlk->baijcdlk', contracted_intermediate) 
    return cc_j_doubles_doubles
