from numpy import einsum
from numpy.typing import NDArray
from chem.hf.ghf_data import GHF_Data
from chem.ccsd.ghf_ccsd import GHF_CCSD_Data


def get_cc_j_doubles_doubles(
    ghf_data: GHF_Data,
    ghf_ccsd_data: GHF_CCSD_Data,
) -> NDArray:
    """ tensor_subscripts: ('a', 'b', 'i', 'j', 'c', 'd', 'k', 'l') """
    f = ghf_data.f
    g = ghf_data.g
    kd =  ghf_data.identity_singles
    v = ghf_data.v
    o = ghf_data.o
    t1 = ghf_ccsd_data.t1
    t2 = ghf_ccsd_data.t2
    
    contracted_intermediate = -1.00 * einsum('ac,bd,ik,lj->abijcdkl', kd[v, v], kd[v, v], kd[o, o], f[o, o], optimize=['einsum_path', (0, 1, 2, 3)])
    cc_j_doubles_doubles =  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,jk,li->abijcdkl', kd[v, v], kd[v, v], kd[o, o], f[o, o], optimize=['einsum_path', (0, 1, 2, 3)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('bd,ik,jl,ac->abijcdkl', kd[v, v], kd[o, o], kd[o, o], f[v, v], optimize=['einsum_path', (0, 1, 2, 3)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abjidckl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,ik,jl,bc->abijcdkl', kd[v, v], kd[o, o], kd[o, o], f[v, v], optimize=['einsum_path', (0, 1, 2, 3)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abjidckl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,ik,jl,mc,bm->abijcdkl', kd[v, v], kd[o, o], kd[o, o], f[o, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,ik,jl,md,bm->abijcdkl', kd[v, v], kd[o, o], kd[o, o], f[o, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,jk,le,ei->abijcdkl', kd[v, v], kd[v, v], kd[o, o], f[o, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bd,jl,ke,ei->abijcdkl', kd[v, v], kd[v, v], kd[o, o], f[o, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,klij->abijcdkl', kd[v, v], kd[v, v], g[o, o, o, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('bd,ik,lacj->abijcdkl', kd[v, v], kd[o, o], g[o, v, v, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abijdclk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('bd,jk,laci->abijcdkl', kd[v, v], kd[o, o], g[o, v, v, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abijdclk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,ik,lbcj->abijcdkl', kd[v, v], kd[o, o], g[o, v, v, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abijdclk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,lbci->abijcdkl', kd[v, v], kd[o, o], g[o, v, v, o], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abijdclk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ik,jl,abcd->abijcdkl', kd[o, o], kd[o, o], g[v, v, v, v], optimize=['einsum_path', (0, 1, 2)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,ik,mlcj,bm->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,ik,mldj,bm->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,klej,ei->abijcdkl', kd[v, v], kd[v, v], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bd,ik,mlej,em->abijcdkl', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,mlci,bm->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->baijcdlk', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,jk,mldi,bm->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,jk,mlei,em->abijcdkl', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, o], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abijcdlk', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->baijcdlk', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ik,jl,macd,bm->abijcdkl', kd[o, o], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('bd,jk,lace,ei->abijcdkl', kd[v, v], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abjidckl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('bd,jl,kace,ei->abijcdkl', kd[v, v], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abjidckl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('bd,ik,jl,mace,em->abijcdkl', kd[v, v], kd[o, o], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abjidckl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,lbce,ei->abijcdkl', kd[v, v], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abjidckl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,jl,kbce,ei->abijcdkl', kd[v, v], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abjidckl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,ik,jl,mbce,em->abijcdkl', kd[v, v], kd[o, o], kd[o, o], g[o, v, v, v], t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->abijdckl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->abjidckl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('jk,mlcd,abim->abijcdkl', kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (1, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('jl,mkcd,abim->abijcdkl', kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (1, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('ik,jl,nmcd,abnm->abijcdkl', kd[o, o], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,klce,ebij->abijcdkl', kd[v, v], g[o, o, v, v], t2, optimize=['einsum_path', (1, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,mlce,ebim->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,jl,mkce,ebim->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('ad,ik,jl,nmce,ebnm->abijcdkl', kd[v, v], kd[o, o], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,klde,ebij->abijcdkl', kd[v, v], g[o, o, v, v], t2, optimize=['einsum_path', (1, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,jk,mlde,ebim->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,jl,mkde,ebim->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('ac,ik,jl,nmde,ebnm->abijcdkl', kd[v, v], kd[o, o], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('ac,bd,klef,efij->abijcdkl', kd[v, v], kd[v, v], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('ac,bd,jk,mlef,efim->abijcdkl', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('ac,bd,jl,mkef,efim->abijcdkl', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, v], t2, optimize=['einsum_path', (0, 1), (1, 2), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ik,jl,nmcd,am,bn->abijcdkl', kd[o, o], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,jk,mlce,bm,ei->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ad,jl,mkce,bm,ei->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ad,ik,jl,nmce,bn,em->abijcdkl', kd[v, v], kd[o, o], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (1, 3), (1, 3), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,jk,mlde,bm,ei->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,jl,mkde,bm,ei->abijcdkl', kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,ik,jl,nmde,bn,em->abijcdkl', kd[v, v], kd[o, o], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (1, 3), (1, 3), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bd,klef,ej,fi->abijcdkl', kd[v, v], kd[v, v], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,bd,jk,mlef,em,fi->abijcdkl', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (1, 2), (1, 3), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bd,jl,mkef,em,fi->abijcdkl', kd[v, v], kd[v, v], kd[o, o], g[o, o, v, v], t1, t1, optimize=['einsum_path', (0, 1), (1, 2), (1, 3), (0, 2), (0, 1)])
    cc_j_doubles_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abijcdkl->abjicdkl', contracted_intermediate)  + -1.00000 * einsum('abijcdkl->baijcdkl', contracted_intermediate)  +  1.00000 * einsum('abijcdkl->bajicdkl', contracted_intermediate) 
    return cc_j_doubles_doubles
