from numpy import einsum
from numpy.typing import NDArray
from chem.hf.intermediates_builders import Intermediates
from chem.ccsd.uhf_ccsd import UHF_CCSD_Data
from chem.ccsd.containers import Spin_MBE, E1_spin, E2_spin


def get_lHtauwCC_singles_aa(
    uhf_scf_data: Intermediates,
    uhf_ccsd_data: UHF_CCSD_Data,
    vector: Spin_MBE,
) -> NDArray:
    """ tensor_subscripts: ('a', 'i') """
    r1_aa = vector.singles[E1_spin.aa]
    r1_bb = vector.singles[E1_spin.bb]
    r2_aaaa = vector.doubles[E2_spin.aaaa]
    r2_abab = vector.doubles[E2_spin.abab]
    r2_abba = vector.doubles[E2_spin.abba]
    r2_baab = vector.doubles[E2_spin.baab]
    r2_baba = vector.doubles[E2_spin.baba]
    r2_bbbb = vector.doubles[E2_spin.bbbb]
    f_aa = uhf_scf_data.f_aa
    f_bb = uhf_scf_data.f_bb
    g_aaaa = uhf_scf_data.g_aaaa
    g_abab = uhf_scf_data.g_abab
    g_bbbb = uhf_scf_data.g_bbbb
    kd_aa =  uhf_scf_data.identity_aa
    kd_bb =  uhf_scf_data.identity_bb
    va = uhf_scf_data.va
    vb = uhf_scf_data.vb
    oa = uhf_scf_data.oa
    ob = uhf_scf_data.ob
    t1_aa = uhf_ccsd_data.t1_aa
    t1_bb = uhf_ccsd_data.t1_bb
    t2_aaaa = uhf_ccsd_data.t2_aaaa
    t2_abab = uhf_ccsd_data.t2_abab
    t2_bbbb = uhf_ccsd_data.t2_bbbb
    if uhf_ccsd_data.lmbda is None:
        raise RuntimeError("Lambda amplitues missing in UHF_CCSD_Data")
    l1_aa = uhf_ccsd_data.lmbda.l1_aa
    l1_bb = uhf_ccsd_data.lmbda.l1_bb
    l2_aaaa = uhf_ccsd_data.lmbda.l2_aaaa
    l2_abab = uhf_ccsd_data.lmbda.l2_abab
    l2_bbbb = uhf_ccsd_data.lmbda.l2_bbbb
    
    lHtauwCC_singles_aa = -1.00 * einsum('jiab,bj->ai', g_aaaa[oa, oa, va, va], r1_aa)
    lHtauwCC_singles_aa +=  1.00 * einsum('ijab,bj->ai', g_abab[oa, ob, va, vb], r1_bb)
    lHtauwCC_singles_aa +=  1.00 * einsum('kiaj,bk,jb->ai', g_aaaa[oa, oa, va, oa], r1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ikaj,bk,jb->ai', g_abab[oa, ob, va, ob], r1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kibj,bk,ja->ai', g_aaaa[oa, oa, va, oa], r1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ikjb,bk,ja->ai', g_abab[oa, ob, oa, vb], r1_bb, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ibac,cj,jb->ai', g_aaaa[oa, va, va, va], r1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ibac,cj,jb->ai', g_abab[oa, vb, va, vb], r1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('jbac,cj,ib->ai', g_aaaa[oa, va, va, va], r1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('bjac,cj,ib->ai', g_abab[va, ob, va, vb], r1_bb, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('lijk,bl,jkab->ai', g_aaaa[oa, oa, oa, oa], r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('iljk,bl,jkab->ai', g_abab[oa, ob, oa, ob], r1_bb, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ilkj,bl,kjab->ai', g_abab[oa, ob, oa, ob], r1_bb, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('kbaj,ck,ijbc->ai', g_aaaa[oa, va, va, oa], r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kbaj,ck,ijcb->ai', g_abab[oa, vb, va, ob], r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('bkaj,ck,ijbc->ai', g_abab[va, ob, va, ob], r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ibcj,ck,kjba->ai', g_aaaa[oa, va, va, oa], r1_aa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ibcj,ck,kjab->ai', g_abab[oa, vb, va, ob], r1_aa, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ibjc,ck,jkab->ai', g_abab[oa, vb, oa, vb], r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('cbad,dj,jicb->ai', g_aaaa[va, va, va, va], r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('cbad,dj,ijcb->ai', g_abab[va, vb, va, vb], r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('bcad,dj,ijbc->ai', g_abab[va, vb, va, vb], r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('kiac,bk,cj,jb->ai', g_aaaa[oa, oa, va, va], t1_aa, r1_aa, l1_aa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ikac,bk,cj,jb->ai', g_abab[oa, ob, va, vb], t1_bb, r1_bb, l1_bb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('kiac,cj,bk,jb->ai', g_aaaa[oa, oa, va, va], t1_aa, r1_aa, l1_aa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ikac,cj,bk,jb->ai', g_abab[oa, ob, va, vb], t1_bb, r1_bb, l1_bb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kjac,bk,cj,ib->ai', g_aaaa[oa, oa, va, va], t1_aa, r1_aa, l1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kjac,bk,cj,ib->ai', g_abab[oa, ob, va, vb], t1_aa, r1_bb, l1_aa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('kjac,ck,bj,ib->ai', g_aaaa[oa, oa, va, va], t1_aa, r1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('jkac,ck,bj,ib->ai', g_abab[oa, ob, va, vb], t1_bb, r1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kibc,cj,bk,ja->ai', g_aaaa[oa, oa, va, va], t1_aa, r1_aa, l1_aa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ikcb,cj,bk,ja->ai', g_abab[oa, ob, va, vb], t1_aa, r1_bb, l1_aa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('kibc,ck,bj,ja->ai', g_aaaa[oa, oa, va, va], t1_aa, r1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ikbc,ck,bj,ja->ai', g_abab[oa, ob, va, vb], t1_bb, r1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('lkaj,bl,ck,ijcb->ai', g_aaaa[oa, oa, va, oa], t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('lkaj,bl,ck,ijbc->ai', g_abab[oa, ob, va, ob], t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('klaj,bl,ck,ijcb->ai', g_abab[oa, ob, va, ob], t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('licj,bl,ck,kjab->ai', g_aaaa[oa, oa, va, oa], t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ilcj,bl,ck,kjab->ai', g_abab[oa, ob, va, ob], t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('iljc,bl,ck,jkab->ai', g_abab[oa, ob, oa, vb], t1_bb, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('lick,cj,bl,jkab->ai', g_aaaa[oa, oa, va, oa], t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ilck,cj,bl,jkab->ai', g_abab[oa, ob, va, ob], t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ilkc,cj,bl,kjab->ai', g_abab[oa, ob, oa, vb], t1_bb, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kcad,bk,dj,jicb->ai', g_aaaa[oa, va, va, va], t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kcad,bk,dj,ijbc->ai', g_abab[oa, vb, va, vb], t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ckad,bk,dj,ijcb->ai', g_abab[va, ob, va, vb], t1_bb, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kbad,dj,ck,jibc->ai', g_aaaa[oa, va, va, va], t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kbad,dj,ck,ijcb->ai', g_abab[oa, vb, va, vb], t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('bkad,dj,ck,ijbc->ai', g_abab[va, ob, va, vb], t1_bb, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ibcd,dj,ck,jkba->ai', g_aaaa[oa, va, va, va], t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ibdc,dj,ck,jkab->ai', g_abab[oa, vb, va, vb], t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ibcd,dj,ck,kjab->ai', g_abab[oa, vb, va, vb], t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('liad,cbjl,dk,jkcb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilad,cbjl,dk,jkcb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('liad,cblj,dk,kjcb->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilad,bcjl,dk,jkbc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('liad,bclj,dk,kjbc->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilad,cbjl,dk,jkcb->ai', g_abab[oa, ob, va, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('liad,dbjk,cl,jkcb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('liad,dbjk,cl,jkcb->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('liad,dbkj,cl,kjcb->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilad,bdjk,cl,jkbc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilad,bdkj,cl,kjbc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilad,dbjk,cl,jkcb->ai', g_abab[oa, ob, va, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('lkad,cbjl,dk,jicb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('lkad,cbjl,dk,jicb->ai', g_abab[oa, ob, va, vb], t2_aaaa, r1_bb, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('lkad,cblj,dk,ijcb->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('lkad,cblj,dk,ijcb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('lkad,bclj,dk,ijbc->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('lkad,bclj,dk,ijbc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.250 * einsum('lkad,cblk,dj,jicb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('lkad,cblk,dj,ijcb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('klad,cbkl,dj,ijcb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('lkad,bclk,dj,ijbc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('klad,bckl,dj,ijbc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('lkad,dbjl,ck,jicb->ai', g_aaaa[oa, oa, va, va], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('lkad,dblj,ck,ijcb->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('klad,bdjl,ck,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('lkad,bdlj,ck,ijbc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('klad,dbjl,ck,ijcb->ai', g_abab[oa, ob, va, vb], t2_bbbb, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('licd,dbjk,cl,jkab->ai', g_aaaa[oa, oa, va, va], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ildc,dbjk,cl,jkab->ai', g_abab[oa, ob, va, vb], t2_aaaa, r1_bb, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('licd,dbjk,cl,jkab->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ildc,dbjk,cl,jkab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('licd,dbkj,cl,kjab->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ildc,dbkj,cl,kjab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('licd,dbjl,ck,jkab->ai', g_aaaa[oa, oa, va, va], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ildc,dbjl,ck,jkab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('licd,dblj,ck,kjab->ai', g_aaaa[oa, oa, va, va], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ilcd,bdjl,ck,jkab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ilcd,dbjl,ck,kjab->ai', g_abab[oa, ob, va, vb], t2_bbbb, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.250 * einsum('licd,cdjk,bl,jkab->ai', g_aaaa[oa, oa, va, va], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ilcd,cdjk,bl,jkab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ilcd,cdkj,bl,kjab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ildc,dcjk,bl,jkab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ildc,dckj,bl,kjab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('lkad,bl,ck,dj,jicb->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 3), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('lkad,bl,ck,dj,ijbc->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('klad,bl,ck,dj,ijcb->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('lkad,bl,dj,ck,jicb->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('lkad,bl,dj,ck,ijbc->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 3), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('klad,bl,dj,ck,ijcb->ai', g_abab[oa, ob, va, vb], t1_bb, t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('licd,bl,dj,ck,jkab->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ildc,bl,dj,ck,jkab->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 3), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ilcd,bl,dj,ck,kjab->ai', g_abab[oa, ob, va, vb], t1_bb, t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('licd,ck,dj,bl,jkab->ai', g_aaaa[oa, oa, va, va], t1_aa, t1_aa, r1_aa, l2_aaaa, optimize=['einsum_path', (0, 3), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ilcd,ck,dj,bl,kjab->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ildc,ck,dj,bl,jkab->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ja,bj,ib->ai', f_aa[oa, va], r1_aa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ib,bj,ja->ai', f_aa[oa, va], r1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('jiab,bckj,kc->ai', g_aaaa[oa, oa, va, va], r2_aaaa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('jiab,bcjk,kc->ai', g_aaaa[oa, oa, va, va], r2_abab, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ijab,cbkj,kc->ai', g_abab[oa, ob, va, vb], r2_abab, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ijab,bckj,kc->ai', g_abab[oa, ob, va, vb], r2_bbbb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('kjab,bckj,ic->ai', g_aaaa[oa, oa, va, va], r2_aaaa, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('kjab,cbkj,ic->ai', g_abab[oa, ob, va, vb], r2_abab, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('jkab,cbjk,ic->ai', g_abab[oa, ob, va, vb], r2_abab, l1_aa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('jibc,bckj,ka->ai', g_aaaa[oa, oa, va, va], r2_aaaa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ijbc,bckj,ka->ai', g_abab[oa, ob, va, vb], r2_abab, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ijcb,cbkj,ka->ai', g_abab[oa, ob, va, vb], r2_abab, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('kiaj,bclk,ljbc->ai', g_aaaa[oa, oa, va, oa], r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ikaj,bclk,ljbc->ai', g_abab[oa, ob, va, ob], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('kiaj,bckl,jlbc->ai', g_aaaa[oa, oa, va, oa], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ikaj,cblk,ljcb->ai', g_abab[oa, ob, va, ob], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('kiaj,cbkl,jlcb->ai', g_aaaa[oa, oa, va, oa], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ikaj,bclk,ljbc->ai', g_abab[oa, ob, va, ob], r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('lkaj,bclk,ijbc->ai', g_aaaa[oa, oa, va, oa], r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('lkaj,bclk,ijbc->ai', g_abab[oa, ob, va, ob], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('klaj,bckl,ijbc->ai', g_abab[oa, ob, va, ob], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('lkaj,cblk,ijcb->ai', g_abab[oa, ob, va, ob], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('klaj,cbkl,ijcb->ai', g_abab[oa, ob, va, ob], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kibj,bclk,ljac->ai', g_aaaa[oa, oa, va, oa], r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ikbj,bclk,ljac->ai', g_abab[oa, ob, va, ob], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kibj,bckl,jlac->ai', g_aaaa[oa, oa, va, oa], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ikjb,cblk,ljac->ai', g_abab[oa, ob, oa, vb], r2_abab, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ikjb,bclk,jlac->ai', g_abab[oa, ob, oa, vb], r2_bbbb, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ibac,cdkj,kjbd->ai', g_aaaa[oa, va, va, va], r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ibac,cdkj,kjbd->ai', g_aaaa[oa, va, va, va], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ibac,cdjk,jkbd->ai', g_aaaa[oa, va, va, va], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ibac,dckj,kjdb->ai', g_abab[oa, vb, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ibac,dcjk,jkdb->ai', g_abab[oa, vb, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ibac,cdkj,kjbd->ai', g_abab[oa, vb, va, vb], r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('jbac,cdkj,kibd->ai', g_aaaa[oa, va, va, va], r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('jbac,cdjk,ikbd->ai', g_aaaa[oa, va, va, va], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('bjac,dckj,kibd->ai', g_abab[va, ob, va, vb], r2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('jbac,dcjk,ikdb->ai', g_abab[oa, vb, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('bjac,cdkj,ikbd->ai', g_abab[va, ob, va, vb], r2_bbbb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ibcd,cdkj,kjba->ai', g_aaaa[oa, va, va, va], r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.250 * einsum('ibcd,cdkj,kjab->ai', g_abab[oa, vb, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.250 * einsum('ibcd,cdjk,jkab->ai', g_abab[oa, vb, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.250 * einsum('ibdc,dckj,kjab->ai', g_abab[oa, vb, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.250 * einsum('ibdc,dcjk,jkab->ai', g_abab[oa, vb, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('liac,bl,cdkj,kjdb->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('liac,bl,cdkj,kjbd->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('liac,bl,cdjk,jkbd->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilac,bl,dckj,kjdb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilac,bl,dcjk,jkdb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ilac,bl,cdkj,kjdb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('kiad,dj,bclk,jlbc->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('kiad,dj,bckl,jlbc->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('kiad,dj,cbkl,jlcb->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ikad,dj,bclk,ljbc->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ikad,dj,cblk,ljcb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ikad,dj,bclk,jlbc->ai', g_abab[oa, ob, va, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ljac,bl,cdkj,kidb->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ljac,bl,cdjk,ikbd->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ljac,bl,dckj,kidb->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ljac,bl,cdkj,ikbd->ai', g_abab[oa, ob, va, vb], t1_aa, r2_bbbb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('jlac,bl,dcjk,ikdb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.250 * einsum('lkad,dj,bclk,jibc->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('lkad,dj,bclk,ijbc->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('klad,dj,bckl,ijbc->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('lkad,dj,cblk,ijcb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('klad,dj,cbkl,ijcb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ljad,dl,bckj,kibc->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ljad,dl,bcjk,ikbc->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('ljad,dl,cbjk,ikcb->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('jlad,dl,bckj,kibc->ai', g_abab[oa, ob, va, vb], t1_bb, r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('jlad,dl,bcjk,ikbc->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('jlad,dl,cbjk,ikcb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.250 * einsum('licd,bl,cdkj,kjab->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ilcd,bl,cdkj,kjab->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ilcd,bl,cdjk,jkab->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ildc,bl,dckj,kjab->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  0.250 * einsum('ildc,bl,dcjk,jkab->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('kibd,dj,bclk,jlac->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('kibd,dj,bckl,jlac->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -1.00 * einsum('ikdb,dj,cblk,jlac->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ikdb,dj,bclk,jlac->ai', g_abab[oa, ob, va, vb], t1_aa, r2_bbbb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_aa +=  1.00 * einsum('ikbd,dj,bclk,ljac->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('libd,dl,bckj,kjac->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('libd,dl,bckj,kjac->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa +=  0.50 * einsum('libd,dl,bcjk,jkac->ai', g_aaaa[oa, oa, va, va], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilbd,dl,bckj,kjac->ai', g_abab[oa, ob, va, vb], t1_bb, r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilbd,dl,bckj,kjac->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ilbd,dl,bcjk,jkac->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ja,bckj,kibc->ai', f_aa[oa, va], r2_aaaa, l2_aaaa, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ja,bcjk,ikbc->ai', f_aa[oa, va], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ja,cbjk,ikcb->ai', f_aa[oa, va], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ib,bckj,kjac->ai', f_aa[oa, va], r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ib,bckj,kjac->ai', f_aa[oa, va], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_aa += -0.50 * einsum('ib,bcjk,jkac->ai', f_aa[oa, va], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    return lHtauwCC_singles_aa


def get_lHtauwCC_singles_bb(
    uhf_scf_data: Intermediates,
    uhf_ccsd_data: UHF_CCSD_Data,
    vector: Spin_MBE,
) -> NDArray:
    """ tensor_subscripts: ('a', 'i') """
    r1_aa = vector.singles[E1_spin.aa]
    r1_bb = vector.singles[E1_spin.bb]
    r2_aaaa = vector.doubles[E2_spin.aaaa]
    r2_abab = vector.doubles[E2_spin.abab]
    r2_abba = vector.doubles[E2_spin.abba]
    r2_baab = vector.doubles[E2_spin.baab]
    r2_baba = vector.doubles[E2_spin.baba]
    r2_bbbb = vector.doubles[E2_spin.bbbb]
    f_aa = uhf_scf_data.f_aa
    f_bb = uhf_scf_data.f_bb
    g_aaaa = uhf_scf_data.g_aaaa
    g_abab = uhf_scf_data.g_abab
    g_bbbb = uhf_scf_data.g_bbbb
    kd_aa =  uhf_scf_data.identity_aa
    kd_bb =  uhf_scf_data.identity_bb
    va = uhf_scf_data.va
    vb = uhf_scf_data.vb
    oa = uhf_scf_data.oa
    ob = uhf_scf_data.ob
    t1_aa = uhf_ccsd_data.t1_aa
    t1_bb = uhf_ccsd_data.t1_bb
    t2_aaaa = uhf_ccsd_data.t2_aaaa
    t2_abab = uhf_ccsd_data.t2_abab
    t2_bbbb = uhf_ccsd_data.t2_bbbb
    if uhf_ccsd_data.lmbda is None:
        raise RuntimeError("Lambda amplitues missing in UHF_CCSD_Data")
    l1_aa = uhf_ccsd_data.lmbda.l1_aa
    l1_bb = uhf_ccsd_data.lmbda.l1_bb
    l2_aaaa = uhf_ccsd_data.lmbda.l2_aaaa
    l2_abab = uhf_ccsd_data.lmbda.l2_abab
    l2_bbbb = uhf_ccsd_data.lmbda.l2_bbbb
    
    lHtauwCC_singles_bb =  1.00 * einsum('jiba,bj->ai', g_abab[oa, ob, va, vb], r1_aa)
    lHtauwCC_singles_bb += -1.00 * einsum('jiab,bj->ai', g_bbbb[ob, ob, vb, vb], r1_bb)
    lHtauwCC_singles_bb += -1.00 * einsum('kija,bk,jb->ai', g_abab[oa, ob, oa, vb], r1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kiaj,bk,jb->ai', g_bbbb[ob, ob, vb, ob], r1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kibj,bk,ja->ai', g_abab[oa, ob, va, ob], r1_aa, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kibj,bk,ja->ai', g_bbbb[ob, ob, vb, ob], r1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('bica,cj,jb->ai', g_abab[va, ob, va, vb], r1_aa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('ibac,cj,jb->ai', g_bbbb[ob, vb, vb, vb], r1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('jbca,cj,ib->ai', g_abab[oa, vb, va, vb], r1_aa, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jbac,cj,ib->ai', g_bbbb[ob, vb, vb, vb], r1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('lijk,bl,jkba->ai', g_abab[oa, ob, oa, ob], r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('likj,bl,kjba->ai', g_abab[oa, ob, oa, ob], r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lijk,bl,jkab->ai', g_bbbb[ob, ob, ob, ob], r1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kbja,ck,jicb->ai', g_abab[oa, vb, oa, vb], r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('bkja,ck,jibc->ai', g_abab[va, ob, oa, vb], r1_bb, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kbaj,ck,ijbc->ai', g_bbbb[ob, vb, vb, ob], r1_bb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('bicj,ck,kjba->ai', g_abab[va, ob, va, ob], r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('bijc,ck,jkba->ai', g_abab[va, ob, oa, vb], r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('ibcj,ck,kjba->ai', g_bbbb[ob, vb, vb, ob], r1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('cbda,dj,jicb->ai', g_abab[va, vb, va, vb], r1_aa, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('bcda,dj,jibc->ai', g_abab[va, vb, va, vb], r1_aa, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('cbad,dj,jicb->ai', g_bbbb[vb, vb, vb, vb], r1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kica,bk,cj,jb->ai', g_abab[oa, ob, va, vb], t1_aa, r1_aa, l1_aa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kiac,bk,cj,jb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r1_bb, l1_bb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kica,cj,bk,jb->ai', g_abab[oa, ob, va, vb], t1_aa, r1_aa, l1_aa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kiac,cj,bk,jb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r1_bb, l1_bb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jkca,bk,cj,ib->ai', g_abab[oa, ob, va, vb], t1_bb, r1_aa, l1_bb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kjac,bk,cj,ib->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r1_bb, l1_bb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kjca,ck,bj,ib->ai', g_abab[oa, ob, va, vb], t1_aa, r1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kjac,ck,bj,ib->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kibc,cj,bk,ja->ai', g_abab[oa, ob, va, vb], t1_bb, r1_aa, l1_bb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kibc,cj,bk,ja->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r1_bb, l1_bb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kicb,ck,bj,ja->ai', g_abab[oa, ob, va, vb], t1_aa, r1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kibc,ck,bj,ja->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lkja,bl,ck,jibc->ai', g_abab[oa, ob, oa, vb], t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('klja,bl,ck,jicb->ai', g_abab[oa, ob, oa, vb], t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('lkaj,bl,ck,ijcb->ai', g_bbbb[ob, ob, vb, ob], t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('licj,bl,ck,kjba->ai', g_abab[oa, ob, va, ob], t1_aa, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lijc,bl,ck,jkba->ai', g_abab[oa, ob, oa, vb], t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('licj,bl,ck,kjab->ai', g_bbbb[ob, ob, vb, ob], t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lick,cj,bl,jkba->ai', g_abab[oa, ob, va, ob], t1_aa, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('likc,cj,bl,kjba->ai', g_abab[oa, ob, oa, vb], t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('lick,cj,bl,jkab->ai', g_bbbb[ob, ob, vb, ob], t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kcda,bk,dj,jibc->ai', g_abab[oa, vb, va, vb], t1_aa, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('ckda,bk,dj,jicb->ai', g_abab[va, ob, va, vb], t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kcad,bk,dj,jicb->ai', g_bbbb[ob, vb, vb, vb], t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kbda,dj,ck,jicb->ai', g_abab[oa, vb, va, vb], t1_aa, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('bkda,dj,ck,jibc->ai', g_abab[va, ob, va, vb], t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kbad,dj,ck,jibc->ai', g_bbbb[ob, vb, vb, vb], t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('bidc,dj,ck,jkba->ai', g_abab[va, ob, va, vb], t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('bicd,dj,ck,kjba->ai', g_abab[va, ob, va, vb], t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('ibcd,dj,ck,jkba->ai', g_bbbb[ob, vb, vb, vb], t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lida,cbjl,dk,jkcb->ai', g_abab[oa, ob, va, vb], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('liad,cbjl,dk,jkcb->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lida,cblj,dk,kjcb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('liad,bcjl,dk,jkbc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lida,bclj,dk,kjbc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('liad,cbjl,dk,jkcb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lida,dbjk,cl,jkcb->ai', g_abab[oa, ob, va, vb], t2_aaaa, r1_aa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lida,dbjk,cl,jkcb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lida,dbkj,cl,kjcb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('liad,bdjk,cl,jkbc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('liad,bdkj,cl,kjbc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('liad,dbjk,cl,jkcb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('klda,cbjl,dk,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lkad,cbjl,dk,jicb->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('klda,bcjl,dk,jibc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lkad,bcjl,dk,jibc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('klda,cbjl,dk,jicb->ai', g_abab[oa, ob, va, vb], t2_bbbb, r1_aa, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lkad,cbjl,dk,jicb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lkda,cblk,dj,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('klda,cbkl,dj,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lkda,bclk,dj,jibc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('klda,bckl,dj,jibc->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.250 * einsum('lkad,cblk,dj,jicb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lkda,dbjl,ck,jibc->ai', g_abab[oa, ob, va, vb], t2_aaaa, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('klda,dbjl,ck,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lkda,dblj,ck,jicb->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lkad,bdjl,ck,jibc->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lkad,dbjl,ck,jicb->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('licd,bdjk,cl,jkba->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('licd,bdjk,cl,jkba->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('licd,bdkj,cl,kjba->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('licd,bdkj,cl,kjba->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('licd,dbjk,cl,jkab->ai', g_abab[oa, ob, va, vb], t2_bbbb, r1_aa, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('licd,dbjk,cl,jkab->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lidc,dbjl,ck,jkba->ai', g_abab[oa, ob, va, vb], t2_aaaa, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lidc,dblj,ck,jkab->ai', g_abab[oa, ob, va, vb], t2_abab, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('licd,bdjl,ck,jkba->ai', g_bbbb[ob, ob, vb, vb], t2_abab, r1_bb, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('licd,bdlj,ck,kjba->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('licd,dbjl,ck,jkab->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('licd,cdjk,bl,jkba->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('licd,cdkj,bl,kjba->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lidc,dcjk,bl,jkba->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lidc,dckj,bl,kjba->ai', g_abab[oa, ob, va, vb], t2_abab, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.250 * einsum('licd,cdjk,bl,jkab->ai', g_bbbb[ob, ob, vb, vb], t2_bbbb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('lkda,bl,ck,dj,jibc->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('klda,bl,ck,dj,jicb->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('lkad,bl,ck,dj,jicb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 3), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lkda,bl,dj,ck,jibc->ai', g_abab[oa, ob, va, vb], t1_aa, t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('klda,bl,dj,ck,jicb->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, r1_aa, l2_abab, optimize=['einsum_path', (0, 3), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lkad,bl,dj,ck,jicb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('lidc,bl,dj,ck,jkba->ai', g_abab[oa, ob, va, vb], t1_aa, t1_aa, r1_bb, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('licd,bl,dj,ck,kjba->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 3), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('licd,bl,dj,ck,jkab->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('licd,ck,dj,bl,kjba->ai', g_abab[oa, ob, va, vb], t1_aa, t1_bb, r1_aa, l2_abab, optimize=['einsum_path', (0, 2), (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('lidc,ck,dj,bl,jkba->ai', g_abab[oa, ob, va, vb], t1_bb, t1_aa, r1_aa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('licd,ck,dj,bl,jkab->ai', g_bbbb[ob, ob, vb, vb], t1_bb, t1_bb, r1_bb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 3), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('ja,bj,ib->ai', f_bb[ob, vb], r1_bb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('ib,bj,ja->ai', f_bb[ob, vb], r1_bb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jiba,bckj,kc->ai', g_abab[oa, ob, va, vb], r2_aaaa, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('jiba,bcjk,kc->ai', g_abab[oa, ob, va, vb], r2_abab, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jiab,cbkj,kc->ai', g_bbbb[ob, ob, vb, vb], r2_abab, l1_aa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('jiab,bckj,kc->ai', g_bbbb[ob, ob, vb, vb], r2_bbbb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('kjba,bckj,ic->ai', g_abab[oa, ob, va, vb], r2_abab, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('jkba,bcjk,ic->ai', g_abab[oa, ob, va, vb], r2_abab, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('kjab,bckj,ic->ai', g_bbbb[ob, ob, vb, vb], r2_bbbb, l1_bb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('jibc,bcjk,ka->ai', g_abab[oa, ob, va, vb], r2_abab, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('jicb,cbjk,ka->ai', g_abab[oa, ob, va, vb], r2_abab, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('jibc,bckj,ka->ai', g_bbbb[ob, ob, vb, vb], r2_bbbb, l1_bb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('kija,bclk,ljbc->ai', g_abab[oa, ob, oa, vb], r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('kiaj,bclk,ljbc->ai', g_bbbb[ob, ob, vb, ob], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('kija,bckl,jlbc->ai', g_abab[oa, ob, oa, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('kiaj,cblk,ljcb->ai', g_bbbb[ob, ob, vb, ob], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('kija,cbkl,jlcb->ai', g_abab[oa, ob, oa, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('kiaj,bclk,ljbc->ai', g_bbbb[ob, ob, vb, ob], r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lkja,bclk,jibc->ai', g_abab[oa, ob, oa, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('klja,bckl,jibc->ai', g_abab[oa, ob, oa, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lkja,cblk,jicb->ai', g_abab[oa, ob, oa, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('klja,cbkl,jicb->ai', g_abab[oa, ob, oa, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lkaj,bclk,ijbc->ai', g_bbbb[ob, ob, vb, ob], r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kibj,bclk,ljca->ai', g_abab[oa, ob, va, ob], r2_aaaa, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kibj,bckl,ljac->ai', g_abab[oa, ob, va, ob], r2_abab, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kibj,cblk,ljca->ai', g_bbbb[ob, ob, vb, ob], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kijb,cbkl,jlca->ai', g_abab[oa, ob, oa, vb], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kibj,bclk,ljac->ai', g_bbbb[ob, ob, vb, ob], r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('bica,cdkj,kjbd->ai', g_abab[va, ob, va, vb], r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('bica,cdkj,kjbd->ai', g_abab[va, ob, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('bica,cdjk,jkbd->ai', g_abab[va, ob, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('ibac,dckj,kjdb->ai', g_bbbb[ob, vb, vb, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('ibac,dcjk,jkdb->ai', g_bbbb[ob, vb, vb, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('ibac,cdkj,kjbd->ai', g_bbbb[ob, vb, vb, vb], r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jbca,cdkj,kidb->ai', g_abab[oa, vb, va, vb], r2_aaaa, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('bjca,cdkj,kibd->ai', g_abab[va, ob, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jbca,cdjk,kibd->ai', g_abab[oa, vb, va, vb], r2_abab, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jbac,dckj,kidb->ai', g_bbbb[ob, vb, vb, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jbac,cdkj,kibd->ai', g_bbbb[ob, vb, vb, vb], r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.250 * einsum('bicd,cdkj,kjba->ai', g_abab[va, ob, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.250 * einsum('bicd,cdjk,jkba->ai', g_abab[va, ob, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.250 * einsum('bidc,dckj,kjba->ai', g_abab[va, ob, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.250 * einsum('bidc,dcjk,jkba->ai', g_abab[va, ob, va, vb], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('ibcd,cdkj,kjba->ai', g_bbbb[ob, vb, vb, vb], r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('lica,bl,cdkj,kjdb->ai', g_abab[oa, ob, va, vb], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lica,bl,cdkj,kjbd->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lica,bl,cdjk,jkbd->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('liac,bl,dckj,kjdb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('liac,bl,dcjk,jkdb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('liac,bl,cdkj,kjdb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('kida,dj,bclk,jlbc->ai', g_abab[oa, ob, va, vb], t1_aa, r2_aaaa, l2_aaaa, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('kida,dj,bckl,jlbc->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('kida,dj,cbkl,jlcb->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('kiad,dj,bclk,ljbc->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('kiad,dj,cblk,ljcb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('kiad,dj,bclk,jlbc->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (2, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('ljca,bl,cdkj,kibd->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('jlca,bl,cdkj,kidb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_aaaa, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('jlca,bl,cdjk,kidb->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('ljac,bl,dckj,kidb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('ljac,bl,cdkj,kidb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lkda,dj,bclk,jibc->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('klda,dj,bckl,jibc->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lkda,dj,cblk,jicb->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('klda,dj,cbkl,jicb->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (1, 3), (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.250 * einsum('lkad,dj,bclk,jibc->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ljda,dl,bckj,kibc->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ljda,dl,cbkj,kicb->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ljda,dl,bckj,kibc->ai', g_abab[oa, ob, va, vb], t1_aa, r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('ljad,dl,bckj,kibc->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('ljad,dl,cbkj,kicb->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('ljad,dl,bckj,kibc->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('licd,bl,cdkj,kjba->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('licd,bl,cdjk,jkba->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lidc,bl,dckj,kjba->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.250 * einsum('lidc,bl,dcjk,jkba->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.250 * einsum('licd,bl,cdkj,kjab->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kidb,dj,cbkl,jlca->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 2), (0, 1), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kibd,dj,bclk,ljca->ai', g_abab[oa, ob, va, vb], t1_bb, r2_aaaa, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kibd,dj,bckl,jlac->ai', g_abab[oa, ob, va, vb], t1_bb, r2_abab, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -1.00 * einsum('kibd,dj,cblk,ljca->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  1.00 * einsum('kibd,dj,bclk,jlac->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lidb,dl,cbkj,kjca->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lidb,dl,cbjk,jkca->ai', g_abab[oa, ob, va, vb], t1_aa, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('lidb,dl,bckj,kjac->ai', g_abab[oa, ob, va, vb], t1_aa, r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('libd,dl,cbkj,kjca->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('libd,dl,cbjk,jkca->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb +=  0.50 * einsum('libd,dl,bckj,kjac->ai', g_bbbb[ob, ob, vb, vb], t1_bb, r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ja,bckj,kibc->ai', f_bb[ob, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ja,cbkj,kicb->ai', f_bb[ob, vb], r2_abab, l2_abab, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ja,bckj,kibc->ai', f_bb[ob, vb], r2_bbbb, l2_bbbb, optimize=['einsum_path', (1, 2), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ib,cbkj,kjca->ai', f_bb[ob, vb], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ib,cbjk,jkca->ai', f_bb[ob, vb], r2_abab, l2_abab, optimize=['einsum_path', (0, 1), (0, 1)])
    lHtauwCC_singles_bb += -0.50 * einsum('ib,bckj,kjac->ai', f_bb[ob, vb], r2_bbbb, l2_bbbb, optimize=['einsum_path', (0, 1), (0, 1)])
    return lHtauwCC_singles_bb
