from numpy import einsum
from numpy.typing import NDArray
from chem.hf.ghf_data import GHF_Data
from chem.ccsd.ghf_ccsd import GHF_CCSD_Data
from chem.meta.ghf_ccsd_mbe import GHF_CCSD_MBE


def get_cc_j_w_doubles(
    ghf_data: GHF_Data,
    ghf_ccsd_data: GHF_CCSD_Data,
    vector: GHF_CCSD_MBE,
) -> NDArray:
    """ tensor_subscripts: ('a', 'b', 'i', 'j') """
    r1 = vector.singles
    r2 = vector.doubles
    f = ghf_data.f
    g = ghf_data.g
    v = ghf_data.v
    o = ghf_data.o
    t1 = ghf_ccsd_data.t1
    t2 = ghf_ccsd_data.t2

    contracted_intermediate =  1.00 * einsum('bi,aj->abij', f[v, o], r1)
    cc_j_w_doubles =  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles += -1.00 * einsum('kk,abij->abij', f[o, o], r2)
    contracted_intermediate = -1.00 * einsum('ki,bk,aj->abij', f[o, o], t1, r1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('bc,ci,aj->abij', f[v, v], t1, r1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles += -1.00 * einsum('kc,ck,abij->abij', f[o, v], t1, r2, optimize=['einsum_path', (0, 1), (0, 1)])
    contracted_intermediate = -1.00 * einsum('kc,cbik,aj->abij', f[o, v], t2, r1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kc,bk,ci,aj->abij', f[o, v], t1, t1, r1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles +=  0.50 * einsum('lklk,abij->abij', g[o, o, o, o], r2)
    contracted_intermediate =  1.00 * einsum('kbci,ck,aj->abij', g[o, v, v, o], t1, r1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('lkci,cblk,aj->abij', g[o, o, v, o], t2, r1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('kbcd,cdik,aj->abij', g[o, v, v, v], t2, r1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles += -0.250 * einsum('lkcd,cdlk,abij->abij', g[o, o, v, v], t2, r2, optimize=['einsum_path', (0, 1), (0, 1)])
    contracted_intermediate =  1.00 * einsum('lkcd,dbil,ck,aj->abij', g[o, o, v, v], t2, t1, r1, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('lkcd,dblk,ci,aj->abij', g[o, o, v, v], t2, t1, r1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('lkcd,bk,cdil,aj->abij', g[o, o, v, v], t1, t2, r1, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkci,bl,ck,aj->abij', g[o, o, v, o], t1, t1, r1, optimize=['einsum_path', (0, 2), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kbcd,ck,di,aj->abij', g[o, v, v, v], t1, t1, r1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles +=  0.50 * einsum('lkcd,ck,dl,abij->abij', g[o, o, v, v], t1, t1, r2, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    contracted_intermediate =  1.00 * einsum('lkcd,bl,ck,di,aj->abij', g[o, o, v, v], t1, t1, t1, r1, optimize=['einsum_path', (0, 2), (0, 3), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('aj,bi->abij', f[v, o], r1)
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles +=  1.00 * einsum('kk,abij->abij', f[o, o], r2)
    contracted_intermediate = -1.00 * einsum('kj,abik->abij', f[o, o], r2)
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('ac,cbij->abij', f[v, v], r2)
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kj,bi,ak->abij', f[o, o], r1, t1, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('ac,bi,cj->abij', f[v, v], r1, t1, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles +=  1.00 * einsum('kc,abij,ck->abij', f[o, v], r2, t1, optimize=['einsum_path', (0, 2), (0, 1)])
    contracted_intermediate = -1.00 * einsum('kc,abik,cj->abij', f[o, v], r2, t1, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kc,cbij,ak->abij', f[o, v], r2, t1, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kc,bi,cajk->abij', f[o, v], r1, t2, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kc,bk,caij->abij', f[o, v], r1, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kc,ci,abjk->abij', f[o, v], r1, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kc,bi,ak,cj->abij', f[o, v], r1, t1, t1, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles += -0.50 * einsum('lklk,abij->abij', g[o, o, o, o], r2)
    contracted_intermediate =  1.00 * einsum('kaij,bk->abij', g[o, v, o, o], r1)
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('abcj,ci->abij', g[v, v, v, o], r1)
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    cc_j_w_doubles +=  0.50 * einsum('lkij,ablk->abij', g[o, o, o, o], r2)
    contracted_intermediate =  1.00 * einsum('kacj,cbik->abij', g[o, v, v, o], r2)
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles +=  0.50 * einsum('abcd,cdij->abij', g[v, v, v, v], r2)
    contracted_intermediate = -1.00 * einsum('lkij,bl,ak->abij', g[o, o, o, o], r1, t1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kacj,bi,ck->abij', g[o, v, v, o], r1, t1, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kacj,bk,ci->abij', g[o, v, v, o], r1, t1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kacj,ci,bk->abij', g[o, v, v, o], r1, t1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('abcd,di,cj->abij', g[v, v, v, v], r1, t1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcj,abil,ck->abij', g[o, o, v, o], r2, t1, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('lkcj,ablk,ci->abij', g[o, o, v, o], r2, t1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcj,cbil,ak->abij', g[o, o, v, o], r2, t1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('kacd,dbij,ck->abij', g[o, v, v, v], r2, t1, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kacd,dbik,cj->abij', g[o, v, v, v], r2, t1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('kacd,cdij,bk->abij', g[o, v, v, v], r2, t1, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('lkcj,bi,calk->abij', g[o, o, v, o], r1, t2, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcj,bl,caik->abij', g[o, o, v, o], r1, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('lkcj,ci,ablk->abij', g[o, o, v, o], r1, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcj,cl,abik->abij', g[o, o, v, o], r1, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('kacd,bi,cdjk->abij', g[o, v, v, v], r1, t2, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  0.50 * einsum('kacd,bk,cdij->abij', g[o, v, v, v], r1, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kacd,di,cbjk->abij', g[o, v, v, v], r1, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kacd,dk,cbij->abij', g[o, v, v, v], r1, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    cc_j_w_doubles +=  0.250 * einsum('lkcd,abij,cdlk->abij', g[o, o, v, v], r2, t2, optimize=['einsum_path', (0, 2), (0, 1)])
    contracted_intermediate = -0.50 * einsum('lkcd,abil,cdjk->abij', g[o, o, v, v], r2, t2, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    cc_j_w_doubles +=  0.250 * einsum('lkcd,ablk,cdij->abij', g[o, o, v, v], r2, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    contracted_intermediate = -0.50 * einsum('lkcd,dbij,calk->abij', g[o, o, v, v], r2, t2, optimize=['einsum_path', (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcd,dbil,cajk->abij', g[o, o, v, v], r2, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('lkcd,dblk,caij->abij', g[o, o, v, v], r2, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    cc_j_w_doubles +=  0.250 * einsum('lkcd,cdij,ablk->abij', g[o, o, v, v], r2, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    contracted_intermediate = -0.50 * einsum('lkcd,cdil,abjk->abij', g[o, o, v, v], r2, t2, optimize=['einsum_path', (0, 1), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcd,bi,dajl,ck->abij', g[o, o, v, v], r1, t2, t1, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcd,bl,daij,ck->abij', g[o, o, v, v], r1, t2, t1, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcd,di,abjl,ck->abij', g[o, o, v, v], r1, t2, t1, optimize=['einsum_path', (0, 3), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('lkcd,bi,dalk,cj->abij', g[o, o, v, v], r1, t2, t1, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcd,bl,daik,cj->abij', g[o, o, v, v], r1, t2, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('lkcd,di,ablk,cj->abij', g[o, o, v, v], r1, t2, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcd,dl,abik,cj->abij', g[o, o, v, v], r1, t2, t1, optimize=['einsum_path', (0, 1), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('lkcd,bi,ak,cdjl->abij', g[o, o, v, v], r1, t1, t2, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -0.50 * einsum('lkcd,bl,ak,cdij->abij', g[o, o, v, v], r1, t1, t2, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcd,di,ak,cbjl->abij', g[o, o, v, v], r1, t1, t2, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcd,dl,ak,cbij->abij', g[o, o, v, v], r1, t1, t2, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcj,bi,al,ck->abij', g[o, o, v, o], r1, t1, t1, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcj,bl,ak,ci->abij', g[o, o, v, o], r1, t1, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('lkcj,ci,ak,bl->abij', g[o, o, v, o], r1, t1, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kacd,bi,ck,dj->abij', g[o, v, v, v], r1, t1, t1, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kacd,bk,cj,di->abij', g[o, v, v, v], r1, t1, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate = -1.00 * einsum('kacd,di,bk,cj->abij', g[o, v, v, v], r1, t1, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles += -0.50 * einsum('lkcd,abij,ck,dl->abij', g[o, o, v, v], r2, t1, t1, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
    contracted_intermediate =  1.00 * einsum('lkcd,abil,ck,dj->abij', g[o, o, v, v], r2, t1, t1, optimize=['einsum_path', (0, 2), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcd,dbij,al,ck->abij', g[o, o, v, v], r2, t1, t1, optimize=['einsum_path', (0, 3), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    cc_j_w_doubles += -0.50 * einsum('lkcd,ablk,cj,di->abij', g[o, o, v, v], r2, t1, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    contracted_intermediate =  1.00 * einsum('lkcd,dbil,ak,cj->abij', g[o, o, v, v], r2, t1, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    cc_j_w_doubles += -0.50 * einsum('lkcd,cdij,ak,bl->abij', g[o, o, v, v], r2, t1, t1, optimize=['einsum_path', (0, 1), (0, 2), (0, 1)])
    contracted_intermediate = -1.00 * einsum('lkcd,bi,al,ck,dj->abij', g[o, o, v, v], r1, t1, t1, t1, optimize=['einsum_path', (0, 3), (1, 3), (1, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate)  + -1.00000 * einsum('abij->baij', contracted_intermediate)  +  1.00000 * einsum('abij->baji', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcd,bl,ak,cj,di->abij', g[o, o, v, v], r1, t1, t1, t1, optimize=['einsum_path', (0, 1), (0, 3), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->baij', contracted_intermediate) 
    contracted_intermediate =  1.00 * einsum('lkcd,di,ak,bl,cj->abij', g[o, o, v, v], r1, t1, t1, t1, optimize=['einsum_path', (0, 1), (0, 3), (0, 2), (0, 1)])
    cc_j_w_doubles +=  1.00000 * contracted_intermediate + -1.00000 * einsum('abij->abji', contracted_intermediate) 
    return cc_j_w_doubles
